# Generated by Django 6.0.6 on 2026-07-27 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='api.department'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='required_by_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
