# Generated by Django 6.0.6 on 2026-08-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_rfq_department_alter_rfq_required_by_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
