# Generated by Django 6.0.6 on 2026-08-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vendor_category_vendor_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='warranty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
