# Generated by Django 6.0.6 on 2026-08-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_quotation_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('under_review', 'Under Review'), ('completed', 'Completed'), ('closed', 'Closed'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
