# Generated by Django 6.0.6 on 2026-08-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_rfq_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='attachment_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax_type',
            field=models.CharField(default='GST_9_9', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
