# Generated by Django 6.0.6 on 2026-08-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_admin_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='changeme', max_length=128),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='password',
            field=models.CharField(default='changeme', max_length=128),
        ),
    ]
