# Generated by Django 6.0.6 on 2026-08-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_purchaseorder_status_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('completed', 'Completed'), ('closed', 'Closed'), ('rejected_by_finance', 'Rejected by Finance'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
